[[redirects]]
  from = "/api/course/*"
  to = "https://course.spacedev.vn/elearning/v4/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/organization/*"
  to = "https://course.spacedev.vn/organization/:splat"
  status = 200
  force = true
    headers = { Access-Control-Allow-Origin = "*" }


[[redirects]]
  from = "/api/user/*"
  to = "https://course.spacedev.vn/users/:splat"
  status = 200
  force = true
    headers = { Access-Control-Allow-Origin = "*" }


[[redirects]]
  from = "/api/auth/*"
  to = "https://course.spacedev.vn/authentication/v2/:splat"
  status = 200
  force = true
    headers = { Access-Control-Allow-Origin = "*" }

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Max-Age = "86400"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200